// gio hang
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";

//category
export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";

// product
export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";

export const FETCH_DELETE_PRODUCT = "FETCH_DELETE_PRODUCT"

export const FETCH_EDIT_PRODUCT = "FETCH_EDIT_PRODUCT";

export const FETCH_UPDATE_PRODUCT = "FETCH_UPDATE_PRODUCT";

export const FETCH_FILTER_PRODUCT = "FETCH_FILTER_PRODUCT";

export const FETCH_SEARCH_PRODUCT = "FETCH_SEARCH_PRODUCT";

export const FETCH_SORT_PRODUCT = "FETCH_SORT_PRODUCT";

export const FETCH_TOTALPage_PRODUCT = "FETCH_TOTALPage_PRODUCT";